# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-phylogenetictree
channels:
  - conda-forge
  - bioconda
  - defaults
  - smirarab
dependencies:


  ## conda-forge packages
  - conda-forge::r-base
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-tidyr=1.1.0
  - conda-forge::r-tidyverse=1.3.0
  
  ## bioconda packages
  - bioconda::bioconductor-ggtree
  - bioconda::bioconductor-treeio
  - bioconda::artic=1.2.1
  - bioconda::mafft=7.475
  - bioconda::iqtree=2.1.2
  - bioconda::newick_utils
  - pip
  - pysam
  - biopython
  - snakemake
  - parallel
  - seqmagick
  - treeshrink
  - ucsc-faFilter
  - ucsc-faSomeRecords
  - ucsc-faSplit
  - fasttree
  - goalign
  - gotree
  - bc
  - bcftools
  - biopython:1.78
  - gofasta
  - easel
  - raxml-ng
  - r-ggplot2
  - r-phangorn
  - r-readr
  - pip:
    - dendropy>=4.4.0
    - pyvcf
    - ncov-parser
    - git+https://github.com/hCoV-2019/lineages.git
    - git+https://github.com/hCoV-2019/pangolin.git
    - git+https://github.com/cov-lineages/pangoLEARN.git
    - git+https://github.com/cov-ert/datafunk.git
    - git+https://github.com/jts/ncov-watch.git
    - git+https://github.com/peterk87/shiptv.git




